DROP SCHEMA `AMCLOUD1`;


CREATE SCHEMA `AMCLOUD1` ;


CREATE TABLE AMCLOUD1.ADDRESS
  (ID NUMERIC(15,0) NOT NULL PRIMARY KEY,
   ADDRESS_1 VARCHAR(30) NULL,
   ADDRESS_2 VARCHAR(30) NULL,
   CITY VARCHAR(20) NULL,
   STATE VARCHAR(2) NULL,
   ZIPCODE VARCHAR(9) NULL,
   ORG_LONGITUDE VARCHAR(20),
   ORG_LATITUDE VARCHAR(20)
   );

CREATE TABLE AMCLOUD1.ORGANIZATION
   (
    ID numeric(15,0) NOT NULL PRIMARY KEY,
    ADDRESS_ID numeric(15,0), 
    NAME  VARCHAR(100),
    DESCRIPTION  VARCHAR(500),
    PHONE1  VARCHAR(20),
    PHONE2  VARCHAR(20),
    FB_TAG VARCHAR(100),
    TWITTER_TAG VARCHAR(100));
   
ALTER TABLE AMCLOUD1.ORGANIZATION
    ADD CONSTRAINT ORGANIZATION_ADDR_FK1 FOREIGN KEY (ADDRESS_ID)
    REFERENCES AMCLOUD1.ADDRESS(ID); 

CREATE TABLE AMCLOUD1.CUSTOMER
   (ID NUMERIC(15,0) NOT NULL PRIMARY KEY,
    ADDRESS_ID numeric(15,0), 
    FIRSTNAME VARCHAR(15) NOT NULL,
    MIDDLENAME VARCHAR(15) NULL,
    LASTNAME VARCHAR(15) NULL,
    USERID VARCHAR(15) NULL,
    PASSWORD VARCHAR(10) NULL ,
    EMAILADDRESS VARCHAR(100) NULL
);

ALTER TABLE AMCLOUD1.CUSTOMER
    ADD CONSTRAINT CUSTOMER_ADDR_FK1 FOREIGN KEY (ADDRESS_ID)
    REFERENCES AMCLOUD1.ADDRESS(ID);


   
CREATE TABLE AMCLOUD1.MENU_CLASS
   (
    CLASS_TYP VARCHAR(50) NOT NULL PRIMARY KEY,
    CLASS_DESC  VARCHAR(500)  
  ); 

CREATE TABLE AMCLOUD1.MENU_ITEM_ATTRIBUTE
  (
   ID NUMERIC(15,0) NOT NULL PRIMARY KEY,
   NO_SELECTION VARCHAR(1) NOT NULL,
   LOW_SPICEY VARCHAR(1) NOT NULL,
   MED_SPICEY VARCHAR(1) NOT NULL,
   REG_SPICEY VARCHAR(1) NOT NULL,
   EXTRA_SPICEY VARCHAR(1) NOT NULL,
   COLD_ITEM VARCHAR(1) NOT NULL,
   HOT_ITEM VARCHAR(1) NOT NULL,
   WARM_ITEM VARCHAR(1) NOT NULL,
   REG_SUGAR VARCHAR(1) NOT NULL,
   LESS_SUGAR VARCHAR(1) NOT NULL,
   NO_SUGAR VARCHAR(1) NOT NULL,
   NO_PEANUTS VARCHAR(1) NOT NULL,
   NO_NUTS VARCHAR(1) NOT NULL,
   FULL_PLATE VARCHAR(1) NOT NULL,
   HALF_PLATE VARCHAR(1) NOT NULL,
   KIDS_PORTION VARCHAR(1) NOT NULL
);

CREATE TABLE AMCLOUD1.MENU_ITEM
   (
    ID NUMERIC(15,0) NOT NULL PRIMARY KEY,
    ATTRIBUTE_ID NUMERIC(15,0) NOT NULL,
    CLASS_TYP VARCHAR(50) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPION VARCHAR(2000) NULL,
    INGREDIENT VARCHAR(2000),
    IMAGE_LINK VARCHAR(512),
    QUANTITY_TYP VARCHAR(10), -- Add a Type table later
    PRICE NUMERIC(8,2),
    CREATE_DATE DATE,
    CREATED_BY VARCHAR(50),
    ONLINE_ELIGIBLE VARCHAR(1)
 );

ALTER TABLE AMCLOUD1.MENU_ITEM
    ADD CONSTRAINT MENU_ITEM_MENU_ITEM_ATTRIBUTE_FK1 FOREIGN KEY (ATTRIBUTE_ID)
    REFERENCES AMCLOUD1.MENU_ITEM_ATTRIBUTE(ID);

ALTER TABLE AMCLOUD1.MENU_ITEM
    ADD CONSTRAINT MENU_ITEM_MENU_CLASS_FK1 FOREIGN KEY (CLASS_TYP)
    REFERENCES AMCLOUD1.MENU_CLASS(CLASS_TYP);

   
CREATE TABLE AMCLOUD1.MENU
   (ID NUMERIC(15,0) NOT NULL PRIMARY KEY,
    MENU_ITEM_ID NUMERIC(15,0) NOT NULL ,
    EFFECTIVE_DATE DATE,
    END_DATE DATE
); 


ALTER TABLE AMCLOUD1.MENU
    ADD CONSTRAINT MENU_MENU_ITEM_FK1 FOREIGN KEY (MENU_ITEM_ID)
    REFERENCES AMCLOUD1.MENU_ITEM(ID);
    


COMMIT;